[project]
name = "explainableckg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.1",
    "owlready2>=0.51",
    "pandas>=3.0.3",
    "rdflib>=7.6.0",
    "torch>=2.13.0",
    "transformers>=5.13.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
